'use strict';

var define = require('../lib/constants/define');

module.exports = define([
    'CHANGE_ROUTE_START',
    'CHANGE_ROUTE_SUCCESS',
    'CHANGE_ROUTE_FAILURE',
    'RECEIVE_HAIRFIE',
    'RECEIVE_BUSINESS',
    'RECEIVE_BUSINESS_SERVICES',
    'RECEIVE_SIMILAR_BUSINESSES',
    'RECEIVE_BUSINESS_REVIEWS',
    'RECEIVE_BUSINESS_REVIEW_REQUEST',
    'RECEIVE_CATEGORIES',
    'RECEIVE_TOP_DEALS',
    'RECEIVE_TOP_HAIRFIES',
    'RECEIVE_STATIONS_NEARBY',
    'RECEIVE_BOOKING',
    'RECEIVE_NOTIFICATION',
    'CLOSE_NOTIFICATION'
]);
