'use strict';

var define = require('../lib/constants/define');

module.exports = define([
    'NAVIGATE_START',
    'NAVIGATE_SUCCESS',
    'NAVIGATE_FAILURE',
    'RECEIVE_HAIRFIE',
    'RECEIVE_BUSINESS',
    'RECEIVE_BUSINESS_SERVICES',
    'RECEIVE_SIMILAR_BUSINESSES',
    'RECEIVE_BUSINESS_REVIEWS',
    'RECEIVE_BUSINESS_REVIEW_REQUEST',
    'RECEIVE_CATEGORIES',
    'RECEIVE_TOP_DEALS',
    'RECEIVE_TOP_HAIRFIES',
    'RECEIVE_STATIONS_NEARBY',
    'RECEIVE_BOOKING',
    'RECEIVE_NOTIFICATION',
    'CLOSE_NOTIFICATION',
    'RECEIVE_ADDRESS_PLACE',
    'RECEIVE_BUSINESS_SEARCH_RESULT',
    'RECEIVE_TOKEN',
    'RECEIVE_BUSINESS_TOP_HAIRFIES',
    'RECEIVE_BUSINESS_HAIRFIES',
    'RECEIVE_HAIRFIE_SEARCH_RESULT',
]);
