<footer>
    <div class="background-footer">
        <a class="social" href="https://www.facebook.com/pages/Hairfie/1507026002849084" target="_blank"><img src="/img/facebook@2x.png" /></a>
        <!--<a class="social" href=""><img src="/img/instagram@2x.png"></a>-->
        <a class="social" href="https://twitter.com/HairfieApp" target="_blank"><img src="/img/twitter@2x.png" /></a>
        <a class="social" href="mailto:hello@hairfie.com" target="_blank"><img src="/img/mail@2x.png" /></a>
    </div>
</footer>